# Generated by Django 5.1 on 2024-09-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='password',
        ),
    ]
