# Generated by Django 5.1 on 2024-10-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_school_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='student_capacity',
        ),
        migrations.AddField(
            model_name='school',
            name='grade_10_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_11_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_12_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_8_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_9_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
