# Generated by Django 5.1 on 2024-10-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_school_student_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='grade_10_enrollment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_11_enrollment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_12_enrollment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_18_enrollment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_9_enrollment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
