# Generated by Django 5.1 on 2024-10-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_school_grade_10_enrollment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='grade_18_enrollment',
            new_name='grade_8_enrollment',
        ),
    ]
