# Generated by Django 5.1 on 2024-10-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_grade_18_enrollment_school_grade_8_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
