# Generated by Django 5.1 on 2024-10-14 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='review',
            new_name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'school')},
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='school.school'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
