# Generated by Django 5.1 on 2024-10-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_rename_review_rating_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='school',
            table='school',
        ),
    ]
