# Generated by Django 5.1 on 2024-09-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0002_pupil_is_active_pupil_is_staff_pupil_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
