# Generated by Django 5.1 on 2024-09-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0003_alter_pupil_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='pupil',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
