# Generated by Django 5.1 on 2024-09-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0005_pupilprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='password',
        ),
        migrations.AddField(
            model_name='pupil',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='grade',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='home_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='PupilProfile',
        ),
    ]
