# Generated by Django 5.1 on 2024-09-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0006_remove_pupil_address_remove_pupil_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupil',
            old_name='contact_number',
            new_name='contact',
        ),
    ]
