# Generated by Django 5.1 on 2024-10-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0008_pupil_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pupil',
            table='pupil',
        ),
    ]
