# Generated by Django 5.1 on 2024-09-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='documents',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='grade_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='health_history',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_school_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='state_province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='student_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='student_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10, null=True),
        ),
    ]
