# Generated by Django 5.1 on 2024-09-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_rename_occupation_application_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='pupil',
        ),
    ]
