# Generated by Django 5.1 on 2024-09-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_remove_application_city_application_pupil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('in_review', 'In Review')], default='Pending', max_length=10),
        ),
    ]
