# Generated by Django 5.1 on 2024-10-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('grade_12', 'Grade 12'), ('grade_11', 'Grade 11'), ('grade_10', 'Grade 10'), ('grade_9', 'Grade 9'), ('grade_8', 'Grade 8')], max_length=50, null=True),
        ),
    ]
