# Generated by Django 5.1 on 2024-10-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_rename_documents_application_appload_results'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='application',
        ),
    ]
