# Generated by Django 5.1 on 2024-11-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_application_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Awaiting_Confirmation', 'Awaiting_Confirmation'), ('Enrolled', 'Enrolled'), ('Rejected', 'Rejected'), ('in_review', 'In Review')], default='Pending', max_length=21),
        ),
    ]
